### ISSUE TITLE
dot character changed to ? mark when saved if copied and pasted back

### ISSUE THREAD

**Issue by ptonino1** [atenfyr/UAssetGUI#10]
Small issue but thought I'd let you know, as I have to use asseteditor.exe to get these back in by copying pasting it from an original file.

(localisation file)
[OT_York_Dungeon_STR.zip](https://github.com/atenfyr/UAssetGUI/files/7377200/OT_York_Dungeon_STR.zip)
.

1. Open export data
2. Open export 2
3. Select stringdictionarydata
4. Go to Text(0) value 3 "・Where's Shionne?"
5. Copy and paste the dot over itself (it sometimes shows as a dot or doesn't paste and shows v instead, try again)
6. When you managed to paste the dot, save file.
7. Reopen saved file, it will appear as ? mark (and also ingame).
Thanks again

**Comment by atenfyr** [comment]
This issue was fixed in atenfyr/UAssetAPI@aeb2bee, and is pending release in alpha 3

**Comment by ptonino1** [comment]
Thanks sorry for that.  I've used your program many hours constantly editing data, and it's never crashed once, you're done a tremendous job.  May I ask if alpha3 will be released soon or is there a way I could compile it, I'm not experienced with this stuff and very eager to continue my mods thanks to your program!

**Comment by atenfyr** [comment]
UAssetAPI & UAssetGUI are pretty straightforward C# projects with limited dependencies, so it doesn't take all that much effort at all to compile it all for yourself if you wanted to. However, I'll probably be releasing alpha 3 in a day or two, since it's been a bit too long since the last alpha

**Comment by ptonino1** [comment]
OK cool thanks, I'm not experienced with how to compile, but I'll see if someone on discord can help me.  Thanks atenfyr!
