### ISSUE TITLE
UAssetGUI-master\UAssetGUI-master\UAssetAPI\UAssetAPI.Tests\UAssetAPI.Tests.csproj : error  : The project file cannot be found

### ISSUE THREAD

**Issue by Pyneappole** [atenfyr/UAssetGUI#109]
Re-downloaded this program onto a new computer, and this whole UAssetAPI folder is empty? I've used this before and had no problem.

**Comment by atenfyr** [comment]
If you're trying to compile UAssetGUI for yourself, you should follow the guide written in the README.md file. Otherwise, you can download a binary from the Releases tab.
