### ISSUE TITLE
Could you please analyze this --------------------------- Uh oh! --------------------------- Failed to maintain binary equality! UAssetAPI may not be able to parse this particular asset correctly, and you may not be able to load this file in-game if modified. 

### ISSUE THREAD

**Issue by Timess** [atenfyr/UAssetGUI#11]
--------------------------- Uh oh! --------------------------- Failed to maintain binary equality! UAssetAPI may not be able to parse this particular asset correctly, and you may not be able to load this file in-game if modified. 

[https://www.mediafire.com/file/lf20tps6iiniy63/18021_LynF.zip/file](https://www.mediafire.com/file/lf20tps6iiniy63/18021_LynF.zip/file)

**Comment by atenfyr** [comment]
I can't do anything without knowing what game the asset was packaged with and what Unreal version the asset was cooked with
