### ISSUE TITLE
UAssetGUI can't parse some Idolm@ster starlit season files correctly and all i get are raw datas.

### ISSUE THREAD

**Issue by ToastyBuns3939** [atenfyr/UAssetGUI#13]
![image](https://user-images.githubusercontent.com/93896872/142892411-14c97f81-2711-41e5-8b25-4f2b680c57b4.png)
![image](https://user-images.githubusercontent.com/93896872/142892532-5f4d0649-b7b2-4966-b724-cbab50d6ebf4.png)

any attempts at saving the files also fails

![image](https://user-images.githubusercontent.com/93896872/143025819-caf06e67-56f5-4c6b-adb0-64a1e381cc1d.png)

Game: IDOLM@STER Starlit Season
UE4 version: 4.24
[Sample files](https://drive.google.com/drive/folders/18syyBo9f7srTaKyyshe9bjLFp6Qi91rX?usp=sharing)

**Comment by trumank** [comment]
Seems to be movie scene related and is fixed in https://github.com/atenfyr/UAssetAPI/commit/cfc001be381e861ca3e2acced512319cefaf2ee2
