### ISSUE TITLE
UassetGUI can't open any Hello Neighbor's alpha 1 assets running on 4.10

### ISSUE THREAD

**Issue by Kksko** [atenfyr/UAssetGUI#15]
I am not able to open assets running on 4.10 and 4.8, pretty sure it also is like that for older versions, but the game I tried it on was Hello Neighbor alpha 1. If you try to open any uasset in HN alpha 1 or pre alpha, you get an error "Encountered an unknown error when trying to open this file! System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: startIndex"
Here's an image of the error and the asset:
https://drive.google.com/file/d/1doSC-pRh7J2flE-pphaH8wSVMQeCuapV/view?usp=sharing

**Comment by atenfyr** [comment]
Partially fixed with atenfyr/uassetapi@d13194b. Full support for older versions of the Unreal Engine will be an ongoing project, since a number of major fundamental differences exist compared to newer versions. Feel free to send in any other assets you have that have significant parsing issues
