### ISSUE TITLE
Can't build the project.

### ISSUE THREAD

**Issue by KiKiHUN1** [atenfyr/UAssetGUI#19]
I followed the steps but still getting this error.
![image](https://user-images.githubusercontent.com/71247943/154853552-a9971fdd-179d-4073-9601-cd2c8e390030.png)

**Comment by atenfyr** [comment]
Update to commits fdf71f0 & atenfyr/UAssetAPI@ca929af, they will let you ignore this error and compile regardless (these pre-build events aren't actually important)
