### ISSUE TITLE
Add command line for opening file & specifying version to open with

### ISSUE THREAD

**Issue by Giwayume** [atenfyr/UAssetGUI#27]
**Describe the solution you'd like**
It looks like the only command line arguments are for json encoding? I'd like to specify the path to a uasset file & version needed to open with on command line.

**Additional context**
Something like:
`uassetgui.exe open path/to/file.uasset VER_UE4_22`

**Comment by atenfyr** [comment]
Command line arguments for opening files have existed since day 1; see [Form1.cs](https://github.com/atenfyr/UAssetGUI/blob/365e1ccb565d68e0fe307bd010ac54c41e39c788/Form1.cs#L256). Added support for specifying version in 365e1cc
