### ISSUE TITLE
[request] search feature

### ISSUE THREAD

**Issue by Itzsmugg** [atenfyr/UAssetGUI#28]
If possible a search feature would be really nice that allows users to search a string and directly open the index in which it is situated.

**Comment by oh-yes-0-fps** [comment]
This or a reference list like in Kaihelios asset editor that tells you what export uses what imports, I'm aware you can get a pseudo version of this using the export information with dependencies column but it's harder to look through that.

**Comment by atenfyr** [comment]
Implemented in commit 2278ec1
