### ISSUE TITLE
Cannot change bIsEnabled value

### ISSUE THREAD

**Issue by oureveryday** [atenfyr/UAssetGUI#30]
**Describe the bug**
Changed .uasset data bIsEnabled to true and packed file using unrealpak. But bIsEnabled is still false in the FModel.
When load .uasset "Failed to parse 11 exports!" happens,and modified .uasset causes game crash.

**Screenshots**
![Error](https://user-images.githubusercontent.com/20489787/179390673-81c9dfc6-b284-4a8d-b5b4-b6ef87204195.jpg)
![Uasset modified](https://user-images.githubusercontent.com/20489787/179390476-c4c81b56-b239-43ca-ad13-f111794e12f1.jpg)
![FModel](https://user-images.githubusercontent.com/20489787/179390478-109e36f2-20ee-4415-b48e-b2fdf27b16eb.jpg)
(After Modified)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: v1.0.0.0-alpha.6 (ebcdfce)
 - Game: Sword and Fairy 7 
 - Game UE4 version: 4.25
 - File: Pal7\Content\UI\UMG\System\UMG_Photo.uasset 

[UMG_Photo.zip](https://github.com/atenfyr/UAssetGUI/files/9127265/UMG_Photo.zip)

**Comment by oureveryday** [comment]
Now: "Failed to parse 8 exports!"

**Comment by LongerWarrior** [comment]
no failed exports in the latest commit [25fe78b](https://github.com/atenfyr/UAssetGUI/commit/25fe78bff192c2f431e9143b65025f14d5fa9673)
