### ISSUE TITLE
Failed to parse 1 export

### ISSUE THREAD

**Issue by Oasis1981** [atenfyr/UAssetGUI#33]
**Describe the bug**
open a RaceSimdataasset.uasset give this error and load 1 row empy. shoud be 197 object
ue 4.27
**To Reproduce**
open file linked

**Expected behavior**
![image](https://user-images.githubusercontent.com/2060157/188940675-82c7e1f5-02df-4f88-bbe5-5b38e440b613.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/2060157/188940075-2810eb0b-d27d-4873-ae9c-11042cf10a1a.png)
![image](https://user-images.githubusercontent.com/2060157/188940158-cc54195c-7cc5-4f5c-bca3-aabfed7c8eef.png)

**Desktop (please complete the following information):**
 - OS: . Windows 11
 - Version or Commit: last. 1.0.0.0 alpha 6/946a8a0

[RaceSimDataAsset.zip](https://github.com/atenfyr/UAssetGUI/files/9508472/RaceSimDataAsset.zip)

**Comment by atenfyr** [comment]
Fixed in atenfyr/UAssetAPI@73b79b0.

As a workaround to restore parsing in earlier versions, go to Edit -> Edit map struct type overrides... and add the following row to the table, then re-open the asset:
`RainChanceMinMaxPerWeatherState | null | Vector2D`
