### ISSUE TITLE
Copy/Paste Multiple Boxes

### ISSUE THREAD

**Issue by Colamitous** [atenfyr/UAssetGUI#34]
Most applications of mine for UAssetGUI result in me having to replace multiple boxes with very similar parameters.

For example, for one of my ACE COMBAT 7: SKIES UNKNOWN mods that edits HUD labels, I have to type the same thing over and over for each individual entity in a given mission. An example I'm doing right now is that there are twelve entities all named the same thing - F/A-18F UNKNOWN. 

Therefore, I have to go through and write the same order of "ObjNameID / StrProperty / us-ascii / F/A-18F" on one line, and on the next line, "CallsignID / StrProperty / us-ascii / UNKNOWN". In other words, I have to fill out eight text boxes in a large uasset file twelve times in a row... and those aren't the only changes I'm making to the file. This has gotten so laggy in the past that I have had to revert to UAssetGUI v1.0.0.3, since that version seems to not have as much issues with editing large umap/uasset files.

I propose a row or column copy/paste feature to fix this issue. Being able to simply copy over every single change from one export to another would save an unbelievable amount of time.

![CopyPasteUassetGUI](https://user-images.githubusercontent.com/113328543/189578819-85eb0a26-794d-4e98-804d-656b874f337e.PNG)

If I could select all eight of those boxes and copy-paste them to all other eleven of those exports instead of writing them out over and over (I have 'StrProperty' currently on my clipboard just for that purpose), it would make workflow a lot easier.

**Comment by atenfyr** [comment]
I added a feature like this last month in commit 186e0d6, which added the ability to copy rows onto the clipboard via UAssetAPI JSON and then paste them in at different locations
