### ISSUE TITLE
Back 4 Blood 4.25d file support and fix?

### ISSUE THREAD

**Issue by kotoricon** [atenfyr/UAssetGUI#35]
The game version is 4.25d and here's the file dump tutorial for this game: https://www.youtube.com/watch?v=oAnQQ06eZRA

Some files always get error like this so the tool cant read it for this game.
![UAssetGUI_YiuLbKcSAu](https://user-images.githubusercontent.com/8659834/194759297-f721c78f-4e4f-4526-a5c3-11a9a6816941.png)

**Comment by atenfyr** [comment]
Please provide a copy of an asset that does not parse with UAssetGUI

**Comment by kotoricon** [comment]
[PlayerCards.zip](https://github.com/atenfyr/UAssetGUI/files/9743744/PlayerCards.zip)
Some of them can be read, some of them dont.

**Comment by atenfyr** [comment]
Fixed in atenfyr/UAssetGUI@7c7191a and atenfyr/UAssetAPI@b025ade
