### ISSUE TITLE
Still some problem for Back 4 Blood uasset file

### ISSUE THREAD

**Issue by kotoricon** [atenfyr/UAssetGUI#37]
Some file always get error like this when open it.
And I ever see another one error window when open it for some file it said error game UE engine version, but I'm sure the game is using 4.25b because there's a bms file dump only work for this game on [cs.rin.ru forum](https://cs.rin.ru/forum/viewtopic.php?f=10&t=100672), maybe I will post it later.
[PlayerCards_TU07_DT.zip](https://github.com/atenfyr/UAssetGUI/files/9844482/PlayerCards_TU07_DT.zip)
![UAssetGUI_zoovCKnv5b](https://user-images.githubusercontent.com/8659834/197342429-7ffcae2d-f9f9-49dc-8d6d-4021a18c5f77.png)

**Comment by atenfyr** [comment]
Unable to replicate in alpha 7, this was probably fixed in atenfyr/UAssetAPI@a5978d9
