### ISSUE TITLE
Failed To Parse 1 export

### ISSUE THREAD

**Issue by LievreAI** [atenfyr/UAssetGUI#39]
i have a game called "sword art online fatal bullet" 
try to open file attached 
[AVID.zip](https://github.com/atenfyr/UAssetGUI/files/9892327/AVID.zip)

i dont know really what to do in this case hope you can help me solved it
any information you thing may help you detect the issue i be glad to let you know
i checked the source and after doing breakpoint i discover the issue came from here
reader.BaseStream.Seek(Exports[i].SerialOffset, SeekOrigin.Begin);

**Comment by atenfyr** [comment]
I cannot help you without knowing what version of the engine the game runs on

**Comment by LievreAI** [comment]
4.17

**Comment by atenfyr** [comment]
Fixed in atenfyr/UAssetAPI@1a43738 and atenfyr/UAssetGUI@f37665f
