### ISSUE TITLE
Failed To Parse Exports

### ISSUE THREAD

**Issue by Velindian** [atenfyr/UAssetGUI#40]
Some exports in UAsset files for SIFU fail to parse when in previous versions of UAssetGUI they parsed.

Last time they parsed was in update v4 with the included "Override.json" applied in the map struct type overrides.
[UAsset Files.zip](https://github.com/atenfyr/UAssetGUI/files/9894731/UAsset.Files.zip)

**Comment by atenfyr** [comment]
I cannot help you without knowing what version of the engine the game runs on

**Comment by Velindian** [comment]
Version: 4.26.2.0
Key: 0x40A266F41FDBCE91312FBB86060D2E9425B7D922C0CF0031F634CAD9AECB49DA
Also, an additional file that hasn't worked since this update.
[Additional File.zip](https://github.com/atenfyr/UAssetGUI/files/9894857/Additional.File.zip)

Let me know any other info you need.

**Comment by atenfyr** [comment]
First issue fixed in atenfyr/UAssetAPI@042e4ef, second issue fixed in atenfyr/UAssetAPI@5cf6c07. Next time, please create a separate issue for any unrelated problems you may have
