### ISSUE TITLE
Failed to parse export

### ISSUE THREAD

**Issue by majorp7** [atenfyr/UAssetGUI#41]
Getting a "Failed to parse 1 exports!" error when trying to open the attached files. Other files work fine.

Game runs on Unreal Engine 4.27
(4.27.7.0, ++UE4+Release-4.27-CL-0)

[DT_BeerStyles.zip](https://github.com/atenfyr/UAssetGUI/files/9930565/DT_BeerStyles.zip)

Windows 10 / UAssetGUI v1.0.0.0-alpha.7

**Comment by LongerWarrior** [comment]
U need to add two MapStruct Overrides
in Edit->Edit map struct type overrides... add
KeyBeerStatRanges | null | FloatRange
CriticalStatRanges | null | FloatRange
![mapstructoverrides](https://user-images.githubusercontent.com/37636768/200300893-71a5845f-845f-49c6-bd4b-d4854b1da3e2.png)
