### ISSUE TITLE
Issues opening two .UAsset on Unreal 4.27 (for Into the Radius)

### ISSUE THREAD

**Issue by Ziggylata** [atenfyr/UAssetGUI#45]
Hello, never made one of these issue reports before so forgive me if I do it wrong.

Currently, UAssetGUI works great for editing Into the Radius assets, however there are two files that are fairly important that do not open correctly with the error: "Failed to parse 1 exports", with the information inside the file being "Raw Data".

I've included some of the files here, if you'd like to open them up and give them a try while diagnosing the issues. 
GameDifficultyConfig works as intended.
GameConfig and PlayerConfig do not.

[IntoTheRadiusUAssets.zip](https://github.com/atenfyr/UAssetGUI/files/10307023/IntoTheRadiusUAssets.zip)

Thank you.

**Comment by LongerWarrior** [comment]
U need to add two MapStruct Overrides
in Edit->Edit map struct type overrides... add (MapName should be without whitespace in the end)
WeightToWarningColor | null | LinearColor
WeaponUnlockMission | null | GameplayTagContainer
![image](https://user-images.githubusercontent.com/37636768/209807410-95787a25-0883-4161-8cb0-db558f40f007.png)

**Comment by Ziggylata** [comment]
This worked for PlayerConfig but not for GameConfig. 

Also, how did you find this information out, so that way other people (including myself in the future) could fix their own issues as they come up?

**Comment by LongerWarrior** [comment]
It should work for other asset too, make sure u copy name without whitespace, also check that table after u reopen uassetgui, sometimes it didn't save properly.

It's hard to explain, but basically each game has few mapproperties with unknown struct type as key or a value. So first i checked if those assets have mapproperty in names array, then find it in hex and based on map name/hex values/struct size i guess right struct type(if u don't want to guess u can try search it in dumps or in runtime with console commands). Also try to build uassetgui from source and debug, so u will u know for sure what's wrong.

**Comment by Ziggylata** [comment]
![image_2022-12-28_092945398](https://user-images.githubusercontent.com/35640182/209827267-313c245b-c7a0-4177-ac13-355bb8d656ea.png)
Check this, this is what I'm referring to. If it's working on yours then I'm having some issue.

**Comment by Ziggylata** [comment]
Using 1.07 with your included MapStruct Overrides has fixed the issue. Thank you. 

For reference, I was using 1.06 because with the amount of editing I was doing, 1.06 will automatically edit the entry when I click one time, 1.07 requires a double click. I used 1.06 to try and save time and never swapped back.
