### ISSUE TITLE
Cant open Days Gone files ue version 4.11

### ISSUE THREAD

**Issue by sEmreCaNw** [atenfyr/UAssetGUI#46]
Days Gone files gives error while opening. ue version 4.11

Added blueprint and mesh samples below.

https://easyupload.io/y3blay

**Comment by atenfyr** [comment]
I can't access the assets at this link. I guess that's my fault, but can you make a new issue with the assets re-uploaded?

**Comment by sEmreCaNw** [comment]
> I can't access the assets at this link. I guess that's my fault, but can you make a new issue with the assets re-uploaded?

will do shortly
