### ISSUE TITLE
Unreal Engine 4.21 DataAsset Parse Fail (Raw Data)

### ISSUE THREAD

**Issue by ssjatys** [atenfyr/UAssetGUI#5]
Hello,

The following DataAsset file (DA_Global.uasset) has a Parse Fail and provide just Raw Data.
I've put everything into a Google Drive Link:
https://drive.google.com/file/d/12EONs0hwwCuxF5Uauqd6YH5ETMV05xcY/view?usp=sharing
- uasset/uexp files
- Screenshots about the error and the raw data
- Heilos' Asset Editor can open it partly
- The asset exported as json file by FModel
- The issue was happened with UAssetGUI v1.0.0.0-alpha.2, OS: Windows 10 x64
- Game is Dragon Ball Z: Kakarot
- Engine: UE 4.21

Thank you

**Comment by atenfyr** [comment]
Issue is not present in newest commit, will be fixed in alpha 3

**Comment by ssjatys** [comment]
Appreciate it, thank you.
