### ISSUE TITLE
cant open the signature file

### ISSUE THREAD

**Issue by Cyberim** [atenfyr/UAssetGUI#50]
”failed to parse this file!
System.FormatException: File signature mismatch“

by the way, I modify Ghostwire Tokyo

**Comment by atenfyr** [comment]
This error message indicates that the file is not a Unreal Engine 4 asset. If the game uses UE5, this is a potential future feature to UAssetAPI; please see atenfyr/UAssetAPI#36. Otherwise, please make sure that you are opening .uasset files instead of .uexp files.
