### ISSUE TITLE
Index of Array out of Range 

### ISSUE THREAD

**Issue by Dastano** [atenfyr/UAssetGUI#52]
**Describe the bug**
---------------------------
Uh oh!
---------------------------
Encountered an unknown error when trying to open this file!
System.ArgumentException: Das Zielarray ist nicht lang genug, um alle Elemente in der Sammlung zu kopieren. Überprüfen Sie Arrayindex und -länge.

**To Reproduce**
Open the asset I attached. 

Version seems to be 4.27.2 

**Expected behavior**
Open the Asset fine.

**Additional context**
(https://mega.nz/file/yER2FJDJ#TL_PNmuWra48feReqWoe9PUralTqJULfWHf24umwkWQ)
https://mega.nz/file/WF4Q3aYD#e5nwG4FpTztyHQXBmaRfRb7dwQi5tnJQtHMksC2L0Rw

**Comment by atenfyr** [comment]
Fixed in atenfyr/UAssetAPI@d5dfcc2

**Comment by Dastano** [comment]
It seems every file has its own garbage data then?

Because you fix, only fixed this one file. I uploaded more samples now. So you can check, if there is a pattern.

Game is Hyenas, just in case.

https://mega.nz/file/6Y5zgCzC#olA0vUpkQ1Jqj5j9qnAqTRsMoeFvFW1gAQo45EZyIp0

Can upload whole Game and sent you in case.
