### ISSUE TITLE
It seems every file has its own garbage data then?

### ISSUE THREAD

**Issue by Dastano** [atenfyr/UAssetGUI#53]
It seems every file has its own garbage data then?

Because your fix, only fixed this one file. I uploaded more samples now. So you can check, if there is a pattern.

Game is Hyenas, just in case.

https://mega.nz/file/6Y5zgCzC#olA0vUpkQ1Jqj5j9qnAqTRsMoeFvFW1gAQo45EZyIp0

Can upload whole Game and sent you in case.

_Originally posted by @Dastano in https://github.com/atenfyr/UAssetGUI/issues/52#issuecomment-1453322345_

**Comment by atenfyr** [comment]
The other files should be fixed by atenfyr/UAssetAPI@e6ef7ba which adjusts the failsafe parameters to be more general, sorry for the confusion
