### ISSUE TITLE
Failed to parse 1 export

### ISSUE THREAD

**Issue by BigBoss0674** [atenfyr/UAssetGUI#57]
When I try to open some assets, I get the error "Failed to parse 1 export" and can't change anything in the Export Data because it's empty.
Game: Lego 2K Drive
UE4 version: 4.27.2.0
I tried latest release: v1.0.0.7 (9418e64 - a5978d9)
Also tried latest build (follow compilation process): v1.0.0.7 (d0773e5 - 79e998b)
OS: Win10
Here are example files:
[assets.zip](https://github.com/atenfyr/UAssetGUI/files/11524745/assets.zip)

**Comment by atenfyr** [comment]
Sorry for the wait! Fixed in atenfyr/UAssetAPI@2aa8334
