### ISSUE TITLE
I keep getting this issue.

### ISSUE THREAD

**Issue by Kyro999** [atenfyr/UAssetGUI#59]
**Describe the bug**
Whenever i try loading an uasset file for a dance from fortnite, it just gives me an error saying "failed to parse this file"

**To Reproduce**
Put in a fortnite uasset file, thats it

**Expected behavior**
It will give you an error thats it

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 22h2
![image](https://github.com/atenfyr/UAssetGUI/assets/81608042/7b19d32e-4031-46cd-8e11-042ed1b03fd6)

**Comment by atenfyr** [comment]
Duplicate of atenfyr/UAssetAPI#36. You may want to consider using [FModel](https://github.com/4sval/FModel), which is specifically built by and for the Fortnite data-mining community
