### ISSUE TITLE
not working about F1 Manager 2022

### ISSUE THREAD

**Issue by lyf67175817** [atenfyr/UAssetGUI#62]
I can't save it back from json to uasset it reported Attempt to add name "FloatRange"to name map during serialization time.

and game will crash when any racer entering traffic lane.

**Comment by lyf67175817** [comment]
crash report :

LoginId:
EpicAccountId:

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000000000a8

F1Manager22
F1Manager22
F1Manager22
F1Manager22
F1Manager22
F1Manager22
F1Manager22
kernel32
ntdll

**Comment by atenfyr** [comment]
Do you have a copy of an asset that experiences this issue? Also, what version of the Unreal Engine does the game use?

**Comment by lyf67175817** [comment]
game are using Unreal Engine 4 but I can't find what version are this game using.
FModel report the Archive Version is VER_UE4_LAST.
[RaceSim.zip](https://github.com/atenfyr/UAssetGUI/files/11780600/RaceSim.zip)

**Comment by atenfyr** [comment]
Thanks for the report - coincidentally, I fixed a bug relating to these assets earlier today with atenfyr/UAssetAPI@2aa8334, and it seems I am able to verify binary equality with these assets with that commit. I have added them to the JSON unit tests for good measure.

**Comment by lyf67175817** [comment]
need update the gui so I can test this shit game can be modding or not.

i'm tired getting crash.

**Comment by fibonatee** [comment]
> Thanks for the report - coincidentally, I fixed a bug relating to these assets earlier today with [atenfyr/UAssetAPI@2aa8334](https://github.com/atenfyr/UAssetAPI/commit/2aa8334), and it seems I am able to verify binary equality with these assets with that commit. I have added them to the JSON unit tests for good measure.

Hello Sir, Could you please update gui for F1 Manager 2023? It's also the binary equality issue. UE version should be 5.1. Thank you!
