### ISSUE TITLE
Could you kindly add support for uasset files of Alien: Dark Descent?

### ISSUE THREAD

**Issue by kangjiajinlong** [atenfyr/UAssetGUI#66]
Currently I cannot open the uasset files of Alien Dark Descent as it always gives me the error:

Failed to parse this file. System.formatexception: file signature mismatch.

**Comment by korgano** [comment]
Contributing some sample .UASSET files from the game to potentially help solve the problem for this game and others.

[BaseManagement.zip](https://github.com/atenfyr/UAssetGUI/files/14069149/BaseManagement.zip)
[AlienClasses.zip](https://github.com/atenfyr/UAssetGUI/files/14069152/AlienClasses.zip)
[Xenotech.zip](https://github.com/atenfyr/UAssetGUI/files/14069153/Xenotech.zip)

**Comment by atenfyr** [comment]
UAssetAPI currently does not have io store/zen support; see atenfyr/UAssetAPI#36
