### ISSUE TITLE
Tree view disappears after multiple searches

### ISSUE THREAD

**Issue by Kronzky** [atenfyr/UAssetGUI#68]
After searching through a file multiple times the tree view becomes invisible, and cannot be restored: https://youtu.be/sNHwp9k9Bs8

Asset file is attached. To repro search for "Intro" about 10 times, and you should see the issue.

(Windows 10, UAssetGUI v1.0.0.8 - never seen the issue happening in 1.0.0.7)

[asset.zip](https://github.com/atenfyr/UAssetGUI/files/12004121/asset.zip)

**Comment by lab313ru** [comment]
The same. It happens on some specific nodes in a list.
