### ISSUE TITLE
can you compile to linux?

### ISSUE THREAD

**Issue by TUNBudi06** [atenfyr/UAssetGUI#71]
i just want run uassetgui on linux since wine are broken with dotnet 4.7.2 or maybe uassetgui cant determine the dotnet version

please compile it on linux

**Comment by TUNBudi06** [comment]
I already solve the issue which IM should using win32 and dotnet472 installed 

Thanks anyway

**Comment by seisdr** [comment]
Jesus..

**Comment by LordFino** [comment]
> I already solve the issue which IM should using win32 and dotnet472 installed
> 
> Thanks anyway

Could you explain how you got it to work? im pretty new to using windows programs on linux :/

**Comment by benjamin-kirkbride** [comment]
https://gist.github.com/benjamin-kirkbride/93c7e60ce83c7d552d2dec147e680fe7
