### ISSUE TITLE
UE 5.3 Support

### ISSUE THREAD

**Issue by magxut** [atenfyr/UAssetGUI#75]
Hey, just wondering if you had any plans to add 5.3 support. Would be a big help as some games have started to upgrade their project to 5.3, and it would be extreamly useful. Thanks

**Comment by Visual917** [comment]
++

**Comment by TheDarkness1994** [comment]
https://github.com/atenfyr/UAssetGUI/releases#:~:text=Today%20is%20the%20three%2Dyear%20anniversary%20of%20UAssetAPI%2C%20so%20it%27s%20a%20good%20time%20for%20me%20to%20finally%20announce%20my%20retirement%20from%20the%20Unreal%20Engine%20modding%20scene%20and%20from%20developing%20UAssetGUI.

**Comment by JoewAlabel** [comment]
> https://github.com/atenfyr/UAssetGUI/releases#:~:text=Today%20is%20the%20three%2Dyear%20anniversary%20of%20UAssetAPI%2C%20so%20it%27s%20a%20good%20time%20for%20me%20to%20finally%20announce%20my%20retirement%20from%20the%20Unreal%20Engine%20modding%20scene%20and%20from%20developing%20UAssetGUI.

This version only goes to 5.2
There r many games using 5.3.2 and there are now the UE 5.4 version.

I tried today with UE 5.3.2 (had select 5.2) and got 2 fails after import mappings.
And another problem i've with alpha 8 is that search always freezes. It do not happen on the earlier version alpha 7 =(

**Comment by atenfyr** [comment]
Duplicate of atenfyr/UAssetAPI#36; UAssetAPI/UAssetGUI in general does not support io store/most UE5 games
