### ISSUE TITLE
Commands to convert uassets to json and then json to uassets

### ISSUE THREAD

**Issue by Maj-ew** [atenfyr/UAssetGUI#78]
So I am trying to understand the API https://atenfyr.github.io/UAssetAPI/api/uassetapi.json.guidjsonconverter.html but I just don't understand most of it.

I am trying to automate my stuff a bit and the point is what would be the command in cmd for example if I wanted to make something like
"path to exe" command "path to file" -EngineVersion [VER_UE4_27] "path to output"

EngineVersion is really the only thing I managed to figure out

I don't know what command would be to "unpack" uassets to json and then "pack" it back. Could anyone help?

**Comment by atenfyr** [comment]
Try using command line parameters:
`UAssetGUI.exe tojson <source> <destination> <engine version> [mappings name]`
`UAssetGUI.exe fromjson <source> <destination> [mappings name]`
e.g.
`UAssetGUI.exe tojson A.uasset B.json VER_UE4_23`
`UAssetGUI.exe fromjson B.json A.uasset VER_UE4_23`
