### ISSUE TITLE
Can I get this fixed so I can edit stuff?

### ISSUE THREAD

**Issue by Peyton2017** [atenfyr/UAssetGUI#83]
Unreal engine 4.26

My only option is to export the data from it to .dat and hex edit. But this limits me a LOT. Here is the uexp, and uasset. I want to add custom skins to a game so people can have new skins on my server, and since I'm not a pro at hex editing, my only hope is that this gets supported.

[DT_CustomizationData.zip](https://github.com/atenfyr/UAssetGUI/files/14661500/DT_CustomizationData.zip)

**Comment by TheDarkness1994** [comment]
![image](https://github.com/atenfyr/UAssetGUI/assets/52470097/7f8416d3-688a-4558-b661-2444aa5f1c81)
Opened it through a text editor. Whether it makes sense for you to open it through this program, I don’t know. I just suggested.
[UE4LocalizationsTool](https://github.com/amrshaheen61/UE4LocalizationsTool)

**Comment by Peyton2017** [comment]
> ![image](https://private-user-images.githubusercontent.com/52470097/314382108-7f8416d3-688a-4558-b661-2444aa5f1c81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjkwMzgsIm5iZiI6MTcxMDkyODczOCwicGF0aCI6Ii81MjQ3MDA5Ny8zMTQzODIxMDgtN2Y4NDE2ZDMtNjg4YS00NTU4LWI2NjEtMjQ0NGFhNWYxYzgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA5NTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YmQwOGIwMTBlODlhYzc3MzAyMzQ3ZGI5M2MzOTgyZDQ5ZTI0MDcwMTJjM2IzM2YzMjcwYzI3MjE3MDY4YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oHAPiTX3jgQhBLlDSNH3YRh1txqCQr0tnCiCgYR6CC8) Opened it through a text editor. Whether it makes sense for you to open it through this program, I don’t know. I just suggested. [UE4LocalizationsTool](https://github.com/amrshaheen61/UE4LocalizationsTool)

I am unable to add data without breaking the file format unfortunately. I've been trying to append my own SteamID to skins, and it doesn't work it just causes my game to crash.

Hopefully the developer of UAssetGUI is able to come up with something to edit this uasset.

**Comment by LongerWarrior** [comment]
@Peyton2017 Fixed in https://github.com/atenfyr/UAssetAPI/commit/42e6d237abfb84501de13e41206b5a87bd0a287b

**Comment by Peyton2017** [comment]
I get this when attempting to build UAssetGUI

Build started...
1>------ Build started: Project: UAssetAPI, Configuration: Debug Verbose Any CPU ------
1>cfc001b
1>C:\Users\Brand\Desktop\UAssetGUI\UAssetAPI\UAssetAPI\UnrealPackage.cs(643,17,643,22): error CS0103: The name 'Debug' does not exist in the current context
1>Done building project "UAssetAPI.csproj" -- FAILED.
2>------ Build started: Project: UAssetAPI.Tests, Configuration: Debug Verbose Any CPU ------
3>------ Build started: Project: UAssetGUI, Configuration: Debug Verbose Any CPU ------
4>------ Build started: Project: UAssetAPI.Benchmark, Configuration: Debug Verbose Any CPU ------
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1217,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK.
4>Done building project "UAssetAPI.Benchmark.csproj" -- FAILED.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1217,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK.
2>Done building project "UAssetAPI.Tests.csproj" -- FAILED.
3>135e990
3>CSC : error CS0006: Metadata file 'C:\Users\Brand\Desktop\UAssetGUI\UAssetAPI\UAssetAPI\bin\Debug Verbose\netstandard2.0\UAssetAPI.dll' could not be found
3>Done building project "UAssetGUI.csproj" -- FAILED.
========== Build: 0 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========

I edited your change from https://github.com/atenfyr/UAssetAPI/commit/42e6d237abfb84501de13e41206b5a87bd0a287b after I downloaded UAssetAPI following the instructions. Any ideas on how to resolve this?

**Comment by Peyton2017** [comment]
> @Peyton2017 Fixed in [atenfyr/UAssetAPI@42e6d23](https://github.com/atenfyr/UAssetAPI/commit/42e6d237abfb84501de13e41206b5a87bd0a287b)

Thank you. I built the project manually and everything seems to show. 
![image](https://github.com/atenfyr/UAssetGUI/assets/28621717/a5ebe4dc-21a3-46d8-b3d4-580c6f3132af)

**Comment by TheDarkness1994** [comment]
Cool, if you have the opportunity to share? In case you need it. Thank you.

**Comment by Peyton2017** [comment]
> @Peyton2017 Fixed in [atenfyr/UAssetAPI@42e6d23](https://github.com/atenfyr/UAssetAPI/commit/42e6d237abfb84501de13e41206b5a87bd0a287b)

Now, would you happen to have a fix for this by chance? 
[DT_MutationsData.zip](https://github.com/atenfyr/UAssetGUI/files/14749438/DT_MutationsData.zip)

This is from the same game. UE 4.26

**Comment by Peyton2017** [comment]
> Cool, if you have the opportunity to share? In case you need it. Thank you.

What do you mean? Download UAssetGUI from source, follow the instructions. Then modify the UAssetAPI installation with the change(s) LongerWarrior has shown above, then build the project.

**Comment by LongerWarrior** [comment]
> > @Peyton2017 Fixed in [atenfyr/UAssetAPI@42e6d23](https://github.com/atenfyr/UAssetAPI/commit/42e6d237abfb84501de13e41206b5a87bd0a287b)
> 
> Now, would you happen to have a fix for this by chance? [DT_MutationsData.zip](https://github.com/atenfyr/UAssetGUI/files/14749438/DT_MutationsData.zip)
> 
> This is from the same game. UE 4.26

U just need correct MapStructOverride(u can generate all needed MapStructOverride with https://github.com/UE4SS-RE/RE-UE4SS), for this particular asset add CustomColors | null | Guid
![image](https://github.com/atenfyr/UAssetGUI/assets/37636768/e2b04732-8707-4546-b642-0495a9ffbf9e)

**Comment by Peyton2017** [comment]
> > > @Peyton2017 Fixed in [atenfyr/UAssetAPI@42e6d23](https://github.com/atenfyr/UAssetAPI/commit/42e6d237abfb84501de13e41206b5a87bd0a287b)
> > 
> > 
> > Now, would you happen to have a fix for this by chance? [DT_MutationsData.zip](https://github.com/atenfyr/UAssetGUI/files/14749438/DT_MutationsData.zip)
> > This is from the same game. UE 4.26
> 
> U just need correct MapStructOverride(u can generate all needed MapStructOverride with https://github.com/UE4SS-RE/RE-UE4SS), for this particular asset add CustomColors | null | Guid ![image](https://private-user-images.githubusercontent.com/37636768/316670420-e2b04732-8707-4546-b642-0495a9ffbf9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MDY3MjgsIm5iZiI6MTcxMTQwNjQyOCwicGF0aCI6Ii8zNzYzNjc2OC8zMTY2NzA0MjAtZTJiMDQ3MzItODcwNy00NTQ2LWI2NDItMDQ5NWE5ZmZiZjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDIyNDAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlODgyZGM0MDNkNTU3YmIyMThkYjQ5OGY0MTNiMzYwOTg5NzUzMmU0OThiNTlhYjViYzMxZWMxMzMxMzJkM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g8WsXuNEbPMQycDnFxQy3yjiQDSx1LqlVk_1e1QW0bQ)

If you wouldn't mind. How did you get that data? I don't see anything about pulling map structs from uasset files

**Comment by LongerWarrior** [comment]
enable GuiConsoleEnabled = 1 and GuiConsoleVisible = 1 in UE4SS-settings.ini and then in Dumpers tab click Generate TMapOverride file, it will generate UassetApi compatible json with all info u need

**Comment by Peyton2017** [comment]
> enable GuiConsoleEnabled = 1 and GuiConsoleVisible = 1 in UE4SS-settings.ini and then in Dumpers tab click Generate TMapOverride file, it will generate UassetApi compatible json with all info u need

Thank you for this information, I really appreciate it. How did you get around the error of "The thread tried to read from or write to a virtual address for which it does not have the appropriate access."?

This seems to be a repetitive issue for me. (Maybe because of EAC, but it's a simple implementation of EAC, a lot of the community gets around it and changes things with CE)

**Comment by LongerWarrior** [comment]
i don't know, alternative method is to find all TMaps in the dump and manually add all info

**Comment by Peyton2017** [comment]
> i don't know, alternative method is to find all TMaps in the dump and manually add all info

How did you find the missing TMap info from just the uasset I gave you? Or do you own the game?

**Comment by LongerWarrior** [comment]
i'm just very good at staring at uasset hex view
identify mappropeprtydata with an error then look on those elements in hex view and guess correct struct
