### ISSUE TITLE
changes not working

### ISSUE THREAD

**Issue by LievreAI** [atenfyr/UAssetGUI#86]
i modify DT_CRaftingData to remove the neccery items to craft items in the game
i did changes the table info its include the materials needed for the craft
everything set to 0 instant from the original number , after i save the file i take 
UnrealPak with the same version engine as the game (UE4.25)
using that UnrealPak-Without-Compression.bat i just dragged the uasset 
its made me Recipe_NoMaterials.pak
and i create a mod folder inside the pak folder and put it but soon as i active the game
i see it didn't change a thing

the file to review it attached 
[DT_CraftingData.zip](https://github.com/atenfyr/UAssetGUI/files/15095086/DT_CraftingData.zip)

**Comment by LongerWarrior** [comment]
rename your pak to Recipe_NoMaterials_P.pak
