### ISSUE TITLE
umap ue 5.1.1

### ISSUE THREAD

**Issue by acyc070** [atenfyr/UAssetGUI#87]
file signature mismatch
i extracted it with fmodel

**Comment by TheDarkness1994** [comment]
> file signature mismatch i extracted it with fmodel

UAssetGUI works with files .uasset .uexp together or .umap and .uexp

**Comment by acyc070** [comment]
fmodel didn't create .uexp

**Comment by TheDarkness1994** [comment]
Yes, I know that FModel cannot completely unpack .ucas .utoc archives, there are some other programs for unpacking with a .uexp file, but another problem may appear, for example limited file support from UAssetGUI or even worse packing all these files back or anything else.
