### ISSUE TITLE
changes don't work 

### ISSUE THREAD

**Issue by ressler779** [atenfyr/UAssetGUI#89]
hello, can you tell me how to properly load a modified digital file through uassetgui into the game? I have nothing, I save the uasset file, then through cmd write it, but the game does not see the changes, do you have a detailed description of how to write new files in the game, Thank you.

**Comment by TheDarkness1994** [comment]
Write the name of the game and, if possible, the version of the UE

**Comment by atenfyr** [comment]
Try consulting other modders and resources for the specific game you are trying to mod
