### ISSUE TITLE
great program, works perfect in most cases but some values don't save right or something is corrupted when saving?

### ISSUE THREAD

**Issue by ptonino1** [atenfyr/UAssetGUI#9]
Making edits to values in BtlSkillDatabase_Arise.uasset (tales of arise), (engine 4.20) editing value with the same original value then saving causes some form of corruption relating to the edit of the item inside the game.  No errors from the program noticed. It would appear only that record is corrupted while others seem to save okay, it's only when you type the same value in the box (or a different value) then save where it corrupts (that specific record).

Earlier versions of uassetgui tested and sometimes gives error, and outcome slightly different where the top half of the record is removed after saving.
[BtlSkillDatabase_Arise.zip](https://github.com/atenfyr/UAssetGUI/files/7377014/BtlSkillDatabase_Arise.zip)

To reproduce:
1. Go to Export Data
2. Expand Export 1
3. Expand Btlskilldatabase
4. Expand Database
5. Expand Record
6. Go to 15th record ID SKILL_ACC_CHANT_DOWN
- Change row 8 Value(0) to same original value.
- Change row 13 Max(0) to same original value.
- Change row 19 FixValue(0) to same original value.

Save file.

**Comment by atenfyr** [comment]
Fixed in latest commit to master, fix will be part of alpha 3

**Comment by ptonino1** [comment]
thanks so much! Very quick response!
