### ISSUE TITLE
Removing the number changing when scrolling 

### ISSUE THREAD

**Issue by humam2104** [atenfyr/UAssetGUI#91]
**Is your feature request related to a problem? Please describe.**
Scrolling while highlighting a number causes the program to change numbers.

**Describe the solution you'd like**
I just wish this could be removed, it's really annoying and I end up changing things I didn't want to change

**Comment by trumank** [comment]
![image](https://github.com/atenfyr/UAssetGUI/assets/1144160/092710e5-8441-488a-834a-a19042b8850a)

**Comment by humam2104** [comment]
Thanks alot for the quick reply! I really appreciate the effort!
