### ISSUE TITLE
does not open .uasset file

### ISSUE THREAD

**Issue by Atamg1994** [atenfyr/UAssetGUI#98]
after updating the game, new files are not edited

I am attaching the files themselves that I got using FModel
[DT_Storage.zip](https://github.com/user-attachments/files/16820078/DT_Storage.zip)

**Comment by Atamg1994** [comment]
The Lord of The Rings: Return to Moria
4.27
![image](https://github.com/user-attachments/assets/69c82032-1fb4-4ad1-9b8c-ae04cff97567)


> > after updating the game, new files are not edited
> > I am attaching the files themselves that I got using FModel [DT_Storage.zip](https://github.com/user-attachments/files/16820078/DT_Storage.zip)
> 
> What is the name of the game? Version Unreal Engine?
The Lord of The Rings: Return to Moria
4.27
![image](https://github.com/user-attachments/assets/69c82032-1fb4-4ad1-9b8c-ae04cff97567)

**Comment by atenfyr** [comment]
Duplicate of atenfyr/UAssetAPI#36, as always
